
import javax.swing.JComboBox;
import java.util.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author khoirul-06990
 */
public class CustomerPembelian extends javax.swing.JFrame {
        
    /**
     * Creates new form CustomerPembelian
     */
    int i = 0;
    public CustomerPembelian() {
        initComponents();
//        ListPesanan.AddRowT(new Object[]{
//            Nama.getText(),(String)cmbBarang.getSelectedItem(),(Integer) jumlahbarang.getValue(),Alamat.getText()
//        });
//        ListPesanan list = new ListPesanan();
//        String nama = Nama.getText();
//        String barang = (String)cmbBarang.getSelectedItem();
//        int jumlah = (Integer) jumlahbarang.getValue();
//        String alamat = Alamat.getText();
//        ArrayList<Pemesanan> pesan = new ArrayList<Pemesanan>();
//        pesan.add(new Pemesanan(Nama.getText(),(String)cmbBarang.getSelectedItem(),Alamat.getText(),(Integer) jumlahbarang.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonbeli = new javax.swing.JButton();
        jumlahbarang = new javax.swing.JSpinner();
        cmbBarang = new javax.swing.JComboBox<>();
        Alamat = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("Barang");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Alamat");

        buttonbeli.setText("Beli");
        buttonbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbeliActionPerformed(evt);
            }
        });

        jumlahbarang.setModel(new javax.swing.SpinnerNumberModel());

        cmbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV", "HandPhone", "Laptop" }));
        cmbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangActionPerformed(evt);
            }
        });

        Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatActionPerformed(evt);
            }
        });

        Back.setText("<- Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(Nama)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(buttonbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jumlahbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(buttonbeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Menu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonbeli() {
        return buttonbeli;
    }

    public void setButtonbeli(JButton buttonbeli) {
        this.buttonbeli = buttonbeli;
    }

    private void buttonbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbeliActionPerformed

        String nama = Nama.getText();
        String barang = (String)cmbBarang.getSelectedItem();
        int jumlah = (Integer) jumlahbarang.getValue();
        String alamat = Alamat.getText();
        
//        Controller control = new Controller(nama, barang, jumlah, alamat);
        Controller.insert(nama, barang, jumlah, alamat);
        JOptionPane.showMessageDialog(this, "Sukses");
//        list.a = i;
//        list.setNama(nama); list.setNamaBarang(barang); list.setJumlahBarang(jumlah); list.setAlamatPemesanan(alamat);
//        DefaultTableModel model = (DefaultTableModel)list.tabel.getModel();
//        model.addRow(new Object[]{Nama.getText(), (String)cmbBarang.getSelectedItem(), (Integer) jumlahbarang.getValue(), Alamat.getText()});
//        DefaultTableModel table = (DefaultTableModel)pesan.tabel.getModel();
//        table.addRow(new Object[]{nama,barang,jumlah,alamat});
//        Object[] a = new Object[]{Nama.getText(),(String)cmbBarang.getSelectedItem(),(Integer) jumlahbarang.getValue(),Alamat.getText()};
//        ListPesanan.AddRowT(a);
//        ListPesanan.AddRowT(Nama.getText(),(String)cmbBarang.getSelectedItem(),(Integer) jumlahbarang.getValue(),Alamat.getText());
//        ListPesanan.AddRowT(new Object[]{
//            Nama.getText(),(String)cmbBarang.getSelectedItem(),(Integer) jumlahbarang.getValue(),Alamat.getText()
//        });
//        l.pack();
//        l.setDefaultCloseOperation(l.DISPOSE_ON_CLOSE);
//        ArrayList<Pemesanan> pesan = new ArrayList<Pemesanan>();
//        pesan.add(new Pemesanan(Nama.getText(),(String)cmbBarang.getSelectedItem(),Alamat.getText(),(Integer) jumlahbarang.getValue()));
//        pesan.add(new Pemesanan("nama","barang","alamat",10));
//        pesan.forEach(data -> {
//        });
//        ListPesanan list = new ListPesanan((String)cmbBarang.getSelectedItem(),Alamat.getText(),Nama.getText(),(Integer) jumlahbarang.getValue());
//         pesan.add(i, element);
//        i++;
        
//        DefaultTableModel model = (DefaultTableModel)ListPesanan.tabel.getModel();
//        model.addRow(new Object[]{
//            Nama.getText(),(String)cmbBarang.getSelectedItem(),(Integer) jumlahbarang.getValue(),Alamat.getText()
//        });
        Customer cus = new Customer();
        cus.setTitle("Customer");
//        ListPesanan.AddRowT(new Object[]{Nama.getText(),(String)cmbBarang.getSelectedItem(),Alamat.getText(),(Integer) jumlahbarang.getValue()});
//        list.pack();
//        list.setDefaultCloseOperation(ListPesanan.DISPOSE_ON_CLOSE);
//        list.setVisible(true);
        cus.setVisible(true);
    }//GEN-LAST:event_buttonbeliActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void cmbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangActionPerformed
//        pesan.setNamaBarang((String)cmbBarang.getSelectedItem());   
    }//GEN-LAST:event_cmbBarangActionPerformed

    private void AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setTitle("Menu");
        menu.setVisible(true); 
    }//GEN-LAST:event_MenuActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Customer cus = new Customer();
        cus.setTitle("Customer");
        cus.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPembelian().setVisible(true);
            }
        });

    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Alamat;
    private javax.swing.JButton Back;
    private javax.swing.JButton Menu;
    public javax.swing.JTextField Nama;
    private javax.swing.JButton buttonbeli;
    public javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JSpinner jumlahbarang;
    // End of variables declaration//GEN-END:variables
}
