/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author khoirul-06990
 */
import java.util.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.AbstractTableModel;
public class ListPesanan extends javax.swing.JFrame {

        ArrayList<Pemesanan> pesan = new ArrayList<Pemesanan>();
//    private DefaultTableModel model;
    String nama, barang, alamat;
    int jumlah,harga;
    /**
     * Creates new form ListPesanan
     */
    
    public ListPesanan() {
        initComponents();
//        model = new DefaultTableModel();
//        TablePesanan.setModel(model);
//        model.addColumn("Nama");
//        model.addColumn("Barang");
//        model.addColumn("Jumlah");
//        model.addColumn("Alamat");
//        model.addColumn("Harga");
    }

//    public ListPesanan(String nama, String barang, String alamat, int jumlah) {
//        this.nama = nama;
//        this.barang = barang;
//        this.alamat = alamat;
//        this.jumlah = jumlah;
//        switch (barang) {
//            case "TV":
//                this.hargaTotal = 1500000 * jumlah;
//                break;
//            case "HandPhone":
//                this.hargaTotal = 2000000 * jumlah;
//                break;
//            case "Laptop":
//                this.hargaTotal = 3500000 * jumlah;
//                break;
//            default:
//                break;
//        }
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePesanan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("<- Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        TablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Barang", "Jumlah", "Alamat", "Harga Total"
            }
        ));
        jScrollPane2.setViewportView(TablePesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Menu))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin();
        admin.setTitle("Admin");
        admin.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setTitle("Menu");
        menu.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

//{pesan.get(i).getNama(), pesan.get(i).getNamaBarang(), pesan.get(i).getJumlahBarang(), pesan.get(i).getAlamatPemesanan(), pesan.get(i).getHargaTotal()}
    public void TablePesanan()
    {
//        for (int i = 0; i<pesan.size(); i++)
//        {
//            for (int a = 0; a<5; a++)
//            {
//                TablePesanan.setValueAt(nama, i, a);
//                TablePesanan.setValueAt(barang, i, a);
//                TablePesanan.setValueAt(jumlah, i, a);
//                TablePesanan.setValueAt(alamat, i, a);
//                TablePesanan.setValueAt(hargaTotal, i, a);
////                Object [] o = new Object [5];
////                o[0] = nama;
////                o[1] = barang;
////                o[2] = jumlah;
////                o[3] = alamat;
////                o[4] = hargaTotal;
////                
//////                model.addRow(o);
//            }
//        }
        for (int i = 0 ; i<pesan.size(); i++)
        {
            nama = pesan.get(i).getNama();
            barang = pesan.get(i).getNamaBarang();
            jumlah = pesan.get(i).getJumlahBarang();
            alamat = pesan.get(i).getAlamatPemesanan();
            harga = pesan.get(i).getHargaTotal();
        }

        ArrayList<Object[]> pes = new ArrayList<Object[]>();
        for (int i = 0; i < pesan.size(); i++) {
            pes.add(i, new Object[] { 
                                      pesan.get(i).getNama(), 
                                      pesan.get(i).getNamaBarang(),
                                      pesan.get(i).getJumlahBarang(),
                                      pesan.get(i).getAlamatPemesanan(),
                                      pesan.get(i).getHargaTotal()
                                  });

        }
        String[] coll = {"Nama", "Barang", "Jumlah", "Alamat", "Harga Total"};
        for(int i = 0; i<pesan.size(); i++)
        {
            {
                pes.get(i);
            }
        }
        
        JTable TablePemesanan = new JTable(, coll);
//        for(int i=0; i<pesan.size();i++)
//        {
//            for(int y=0; y<5; y++)
//            {
//                TablePesanan.setValueAt(pes, i, y);
//            }
//        }
        
}

    
//    public void ListPesanan(List<Pemesanan> pesan)
//    {
//        this.pesan = pesan;
//    }
    
//    public void Data(Pemesanan pes)
//    {
//        pesan.add(pes);
//        TablePesanan.getModel().
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPesanan().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Menu;
    private javax.swing.JTable TablePesanan;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
   
}
