/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author khoirul-06990
 */
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableModel;
//import javax.swing.table.AbstractTableModel;
public class ListPesanan extends javax.swing.JFrame {
        private String namaBarang, alamatPemesanan, nama;
        private int jumlahBarang, hargaTotal;
        ArrayList<Pemesanan> pes = new ArrayList<Pemesanan>();
        static CustomerPembelian cus = new CustomerPembelian();
        public static Object[] d ;
        public int a;
        
//    d[] = new Object[]{};
    public ListPesanan() {
        initComponents();
//        Controller c = new Controller();
////        Object[] data = 
//        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        model.addRow(c.data());
//        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        model.insertRow(a, d);
//        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        model.addRow(new Object[]{
//            nama, namaBarang, jumlahBarang, alamatPemesanan, hargaTotal
//        });
//        for (int i = 0; i<pes.size(); i++){
//        d = pes.get(i).Add();}
//        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        model.addRow(d);
//        List<Object> list = new ArrayList<>();
//            for (int i=0; i<pes.size(); i++) {
//                list.add(new Object[]{pes.get(i).getNama(),pes.get(i).getNamaBarang(),pes.get(i).getJumlahBarang(),pes.get(i).getAlamatPemesanan()});
//            }
//            DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//            for (int i = 0; i<list.size();i++) {
//                model.addRow((Object[]) list.get(i));
//            }
//        ArrayList<Pemesanan> pesan = new ArrayList<Pemesanan>();
//        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        pesan.forEach(data -> {
//            model.addRow(new Object[]{
//                data.getNama(), data.getNamaBarang(),data.getJumlahBarang()
//                });
//        });
//        model.addRow(new Object[][]={
//        {nama},{namaBarang},{jumlahBarang}
//
//    });
//    CustomerPembelian c = new CustomerPembelian();
//    c.pack();
//    c.setLocationRelativeTo(null);
//    c.setDefaultCloseOperation(c.DISPOSE_ON_CLOSE);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updatename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbupdate = new javax.swing.JComboBox<>();
        Update = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("<- Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Barang", "Jumlah", "Alamat", "Harga", "Status"
            }
        ));
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel.setName(""); // NOI18N
        tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabel);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Update Status Kiriman");

        jLabel2.setText("Nama");

        jLabel3.setText("Status");

        cmbupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disiapkan", "Dikirim", "Diterima" }));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setText("List Pemesanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(45, 45, 45)
                                    .addComponent(updatename, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(Update))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Back)
                        .addGap(176, 176, 176)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 187, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(jLabel4)
                    .addContainerGap(543, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back)
                            .addComponent(Menu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(updatename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(27, 27, 27)
                        .addComponent(Update)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel4)
                    .addContainerGap(214, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin();
        admin.setTitle("Admin");
        admin.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setTitle("Menu");
        menu.setVisible(true);
//    CustomerPembelian c = new CustomerPembelian();
//    c.setVisible(true);
//    c.pack();
//    c.setLocationRelativeTo(null);
//    c.setDefaultCloseOperation(c.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_MenuActionPerformed

//    public static void AddRowT(String nama,String barang,int jumlah,String alamat)
//    {
//                d[0] = nama;
//                d[1] = barang;
//                d[2] = jumlah;
//                d[3] = alamat;
////                d[i][4] = pesan.get(i).getHargaTotal();
////            }
//    }
//    
    
    private void tabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelAncestorAdded
        // TODO add your handling code here:
        Controller c = new Controller();
        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        for (int i=0; i<Controller.kirim.size(); i++)
//        {
//            model.addRow(Controller.data());
//        }
        for (int i=0; i<Controller.kirim.size(); i++)
        {
            model.addRow(new Object[]{Controller.kirim.get(i).getNama(),
                Controller.kirim.get(i).getNamaBarang(),
                Controller.kirim.get(i).getJumlahBarang(),
                Controller.kirim.get(i).getAlamatPemesanan(),
                Controller.kirim.get(i).getHargaTotal(),
                Controller.kirim.get(i).getStatus()
            });
        }
//        for(Object[] row : Controller.data())
//        {
//            model.addRow(row);
//        }
//        model.addRow(
//            for (Kiriman kirim : Controller.kirim) {
//            }
//        );
//        model.insertRow(tabel.getRowCount(), c.data());
//        for(int i = 0; i<c.kirim.size(); i++)
//        {
//            Object[] row= {c.kirim.get(i).getNama()};
//            model.addRow(new Object[]{c.data()});
//        }
//        for (Object k : c.data())
//        {
//            model.addRow(();
//        }
        
        //        model.insertRow(ERROR, d);
        //        int a =0;
        //        while(nama!=null){
            //        tabel.getModel().setValueAt(nama, 1, 1);
            //
            //        }
        //        List<Object> list = new ArrayList<>();
        //            for (int i=0; i<pes.size(); i++) {
            //                list.add(new Object[]{pes.get(i).getNama(),pes.get(i).getNamaBarang(),pes.get(i).getJumlahBarang(),pes.get(i).getAlamatPemesanan()});
            //            }
        //   *     DefaultTableModel model = (DefaultTableModel)tabel.getModel();
        //   *     model.addRow(new Object[]{cus.Nama.getText(),cus.cmbBarang.getSelectedItem(),cus.jumlahbarang.getValue(),cus.Alamat.getText(),1000,"dikirim"});
        ////        model.addRow(new Object[][]={
            ////        {nama,namaBarang,jumlahBarang},});
    //            for (Object p : list) {
        //                model.addRow((Object[])p);
        //            }
//        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//        model.addRow(d);
    }//GEN-LAST:event_tabelAncestorAdded

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        int i = 0;
        while(!Controller.kirim.get(i).getNama().equals(updatename.getText()))
        {
            i++;
        }
        if(Controller.kirim.get(i).getNama().equals(updatename.getText()))
        {
//            Controller.kirim.get(i).setStatus((String)cmbupdate.getSelectedItem());
            Controller.updateStatus(i,updatename.getText(),
                    Controller.kirim.get(i).getNamaBarang(),
                    Controller.kirim.get(i).getJumlahBarang(),
                    Controller.kirim.get(i).getAlamatPemesanan(),
                    (String)cmbupdate.getSelectedItem());
        }
        JOptionPane.showMessageDialog(this, "TERUPDATE");
    }//GEN-LAST:event_UpdateActionPerformed


//    public static void AddRowT(Object[] data)
//    {
//        
////        DefaultTableModel model = (DefaultTableModel)tabel.getModel();
//////        model.addRow(new Object[]{cus.Nama.getText(),cus.cmbBarang.getSelectedItem(),cus.jumlahbarang.getValue(),cus.Alamat.getText(),1000,"dikirim"});
////        model.addRow(data);
//        d = data;
//    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPesanan().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> cmbupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabel;
    private javax.swing.JTextField updatename;
    // End of variables declaration//GEN-END:variables
   
}
